[workspace]
authors = ["Luca D'Angelo <ldgaetano@protonmail.com>"]
channels = ["conda-forge"]
name = "gluon_sims"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
pygluon = ">=1.0.0, <2"
ipykernel = ">=7.1.0, <8"
